// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Soyuen/go-redis-chat-server/internal/application/realtime (interfaces: Connection)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	realtime "github.com/Soyuen/go-redis-chat-server/internal/application/realtime"
	gomock "github.com/golang/mock/gomock"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// HandleConnection mocks base method.
func (m *MockConnection) HandleConnection(arg0 realtime.WSConn, arg1 string, arg2 func([]byte) *realtime.Message, arg3 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleConnection", arg0, arg1, arg2, arg3)
}

// HandleConnection indicates an expected call of HandleConnection.
func (mr *MockConnectionMockRecorder) HandleConnection(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnection", reflect.TypeOf((*MockConnection)(nil).HandleConnection), arg0, arg1, arg2, arg3)
}
