// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/realtimeiface/broadcast.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	realtimeiface "github.com/Soyuen/go-redis-chat-server/pkg/realtimeiface"
	gomock "github.com/golang/mock/gomock"
)

// MockBroadcaster is a mock of Broadcaster interface.
type MockBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcasterMockRecorder
}

// MockBroadcasterMockRecorder is the mock recorder for MockBroadcaster.
type MockBroadcasterMockRecorder struct {
	mock *MockBroadcaster
}

// NewMockBroadcaster creates a new mock instance.
func NewMockBroadcaster(ctrl *gomock.Controller) *MockBroadcaster {
	mock := &MockBroadcaster{ctrl: ctrl}
	mock.recorder = &MockBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcaster) EXPECT() *MockBroadcasterMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockBroadcaster) Broadcast(message []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockBroadcasterMockRecorder) Broadcast(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockBroadcaster)(nil).Broadcast), message)
}

// CloseAllClients mocks base method.
func (m *MockBroadcaster) CloseAllClients() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAllClients")
}

// CloseAllClients indicates an expected call of CloseAllClients.
func (mr *MockBroadcasterMockRecorder) CloseAllClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAllClients", reflect.TypeOf((*MockBroadcaster)(nil).CloseAllClients))
}

// Register mocks base method.
func (m *MockBroadcaster) Register(client realtimeiface.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", client)
}

// Register indicates an expected call of Register.
func (mr *MockBroadcasterMockRecorder) Register(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBroadcaster)(nil).Register), client)
}

// Unregister mocks base method.
func (m *MockBroadcaster) Unregister(client realtimeiface.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", client)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockBroadcasterMockRecorder) Unregister(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockBroadcaster)(nil).Unregister), client)
}
