// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Soyuen/go-redis-chat-server/internal/application/realtime (interfaces: ChannelManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	realtime "github.com/Soyuen/go-redis-chat-server/internal/application/realtime"
	gomock "github.com/golang/mock/gomock"
)

// MockChannelManager is a mock of ChannelManager interface.
type MockChannelManager struct {
	ctrl     *gomock.Controller
	recorder *MockChannelManagerMockRecorder
}

// MockChannelManagerMockRecorder is the mock recorder for MockChannelManager.
type MockChannelManagerMockRecorder struct {
	mock *MockChannelManager
}

// NewMockChannelManager creates a new mock instance.
func NewMockChannelManager(ctrl *gomock.Controller) *MockChannelManager {
	mock := &MockChannelManager{ctrl: ctrl}
	mock.recorder = &MockChannelManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelManager) EXPECT() *MockChannelManagerMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockChannelManager) Broadcast(arg0 realtime.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", arg0)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockChannelManagerMockRecorder) Broadcast(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockChannelManager)(nil).Broadcast), arg0)
}

// CloseAllChannels mocks base method.
func (m *MockChannelManager) CloseAllChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAllChannels")
}

// CloseAllChannels indicates an expected call of CloseAllChannels.
func (mr *MockChannelManagerMockRecorder) CloseAllChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAllChannels", reflect.TypeOf((*MockChannelManager)(nil).CloseAllChannels))
}

// CloseChannel mocks base method.
func (m *MockChannelManager) CloseChannel(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseChannel", arg0)
}

// CloseChannel indicates an expected call of CloseChannel.
func (mr *MockChannelManagerMockRecorder) CloseChannel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseChannel", reflect.TypeOf((*MockChannelManager)(nil).CloseChannel), arg0)
}

// GetOrCreateChannel mocks base method.
func (m *MockChannelManager) GetOrCreateChannel(arg0 string) realtime.Broadcaster {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateChannel", arg0)
	ret0, _ := ret[0].(realtime.Broadcaster)
	return ret0
}

// GetOrCreateChannel indicates an expected call of GetOrCreateChannel.
func (mr *MockChannelManagerMockRecorder) GetOrCreateChannel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateChannel", reflect.TypeOf((*MockChannelManager)(nil).GetOrCreateChannel), arg0)
}
